### ISSUE TITLE
Roadmap to v1.0

### ISSUE THREAD

**Issue by natelandau** [natelandau/obsidian-metadata#11]
Roadmap for features as I work towards v1.0  

Let me know what you'd like added.

- [X] Add new frontmatter
- [x] Increase options for filtering which notes are included in scope
- [x] Add new inline metadata
- [x] Add new inline tags
- [x] Better tools to inspect metadata within a vault
- [x] Reorganize metadata between types (ie - move key/values between inline and frontmatter)
- [x] Reorganize inline metadata within notes (ie - move to top, bottom, callout, etc.)
- [x] CSV imports of metadata
- [x] JSON and CSV exports of metadata

**Comment by gapmiss** [comment]
I would like a non-GUI command, or option in the GUI, to export all the metadata to stdout or file. Thank you.

**Comment by natelandau** [comment]
@gapmiss what type of file?  csv?

**Comment by gapmiss** [comment]
If you are planning on CSV imports, it would probably make sense to export CSV also. Otherwise, JSON is preferred.

**Comment by natelandau** [comment]
CSV and JSON exports now available via CLI and GUI

**Comment by gapmiss** [comment]
Thank you for the CSV/JSON export. Initial testing has been problem-free.

**Comment by natelandau** [comment]
gonna kick the tires for a few days and then release v1
